import type { Tactic, Stakeholder } from "./types";

export const TACTICS: Tactic[] = [
  {
    id: "demo",
    label: "Live Demo",
    short: "DEMO",
    color: "#5fc5f8",
    hotkey: "1",
    blurb: "Show, don't tell. Strong against engineers and directors who need to see it work.",
    strongAgainst: ["skepticEng", "director"],
  },
  {
    id: "pilot",
    label: "Pilot Program",
    short: "PILOT",
    color: "#0081BC",
    hotkey: "2",
    blurb: "De-risk with a small bet. Strong against budget holders and process hoarders.",
    strongAgainst: ["budget", "process"],
  },
  {
    id: "interview",
    label: "User Interview",
    short: "TALK",
    color: "#F3E8B9",
    hotkey: "3",
    blurb: "Listen first. Strong against frustrated customers and the old guard.",
    strongAgainst: ["customer", "director"],
  },
  {
    id: "data",
    label: "Data Insight",
    short: "DATA",
    color: "#6D5592",
    hotkey: "4",
    blurb: "Numbers don't lie. Strong against budget holders and VPs of Status Quo.",
    strongAgainst: ["budget", "vp"],
  },
  {
    id: "quickwin",
    label: "Quick Win",
    short: "WIN",
    color: "#9bd9ff",
    hotkey: "5",
    blurb: "Build momentum. Strong against process hoarders and skeptical engineers.",
    strongAgainst: ["process", "skepticEng"],
  },
];

export const STAKEHOLDERS: Record<string, Stakeholder> = {
  skepticEng: {
    id: "skepticEng",
    label: "Skeptical Engineer",
    short: "ENG",
    color: "#5fc5f8",
    resistance: 2,
    points: 100,
    blurb: "“Has anyone benchmarked this?”",
  },
  budget: {
    id: "budget",
    label: "Budget Holder",
    short: "$$$",
    color: "#F3E8B9",
    resistance: 3,
    points: 150,
    blurb: "“What's the ROI?”",
  },
  customer: {
    id: "customer",
    label: "Frustrated Customer",
    short: "USR",
    color: "#d4546c",
    resistance: 2,
    points: 120,
    blurb: "“The old way worked fine.”",
  },
  director: {
    id: "director",
    label: "Old-Guard Director",
    short: "DIR",
    color: "#6D5592",
    resistance: 3,
    points: 180,
    blurb: "“We tried this in 2014.”",
  },
  process: {
    id: "process",
    label: "Process Hoarder",
    short: "PRC",
    color: "#9bd9ff",
    resistance: 2,
    points: 130,
    blurb: "“Where's the SOP?”",
  },
  vp: {
    id: "vp",
    label: "VP of Status Quo",
    short: "VP",
    color: "#013B72",
    resistance: 5,
    points: 400,
    blurb: "“Let's revisit next quarter.”",
  },
};
