// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/AccessibilityFirst.tsx": () => import("../components/mockups/hero-variants/AccessibilityFirst.tsx"),
  "./components/mockups/hero-variants/AffordanceFirst.tsx": () => import("../components/mockups/hero-variants/AffordanceFirst.tsx"),
  "./components/mockups/hero-variants/HierarchyClear.tsx": () => import("../components/mockups/hero-variants/HierarchyClear.tsx")
};
